# build image:
#   docker build -f client/Dockerfile.dev -t 0xend-client-dev .
# run container:
#   docker run -it --rm -p 3000:3000 0xend-client-dev

# Use latest lightweight node release version
FROM node:22-alpine
LABEL stage="development"

# Set working directory inside the container
# This is a monorepo, so we need client/server folders
WORKDIR /app

#### Dependency layer
# Copy shared configs (monorepo layout)
COPY package*.json ./
COPY tsconfig.json .

COPY client/package*.json ./client/
RUN npm install

#### Source layer
# NOTE: be sure to maintain .dockerignore
COPY client/ ./client

# Expose the React dev server port
EXPOSE 3000

# Start React app in dev mode with hot reloading
WORKDIR /app/client
CMD ["npm", "run", "dev"]
