# build image:
#   docker build -f client/Dockerfile.dev -t 0xend-client-dev .
# run container:
#   docker run -it --rm -p 3000:3000 0xend-client-dev

# Use latest lightweight node release version
FROM node:22-alpine
LABEL stage="development"

# Set working directory inside the container
# This is a monorepo, so we need client/server folders
WORKDIR /app/client

#### Dependency layer
# Copy shared config
COPY tsconfig.json /app/tsconfig.json
COPY client/package*.json ./

RUN npm install

#### Source layer
# NOTE: be sure to maintain .dockerignore
COPY client/ .

# Expose the React dev server port
EXPOSE 3000

# Start React app in dev mode with hot reloading
CMD ["npm", "run", "dev"]
