# build image:
#   docker build -f server/Dockerfile.dev -t 0xend-server-dev .
# run container:
#   docker run -it --rm -p 3001:3001 0xend-server-dev

# Use latest lightweight node release version
FROM node:22-alpine
LABEL stage="development"

# Set working directory inside the container
# This is a monorepo, so we need server/server folders
WORKDIR /app

#### Dependency layer
# Copy shared configs (monorepo layout)
COPY package*.json ./
COPY tsconfig.json .

COPY server/package*.json ./server/
RUN npm install

#### Source layer
# NOTE: be sure to maintain .dockerignore
COPY server/ ./server

# Expose the express dev server port
EXPOSE 3001

# Start express in dev mode with hot reloading
WORKDIR /app/server
CMD ["npm", "run", "dev"]
